substitutions:
  name: "media-player"
  friendly_name: "Media Player"
  media_player: ""

esphome:
  name_add_mac_suffix: true

packages:
  music_dashboard: !include ../devices/esp32-2432s028/packages.yaml

wifi:
  ap:

captive_portal:
